# Generated by Django 4.2.4 on 2023-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
