# Generated by Django 4.2.4 on 2023-10-05 16:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articles_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
